### ISSUE TITLE
Infix extension functions

### ISSUE THREAD

**Issue by angelbirth** [romainguy/kotlin-math#17]
instead of 
`inline fun lessThan(a: Float2, b: Float) = Bool2(a.x < b, a.y < b)`, 
why not make it
`inline infix fun Float2.lessThan(b: Float) = Bool2(x < b, y < b)` ?
That way, we can call it `if (v lessThan 1f) ...`

**Comment by romainguy** [comment]
I wanted to follow the GLSL convention to make code more easily portable. But both could be implemented.

**Comment by angelbirth** [comment]
oh, right. but they both have the same jvm signature, so only one could exist

**Comment by romainguy** [comment]
How about using shorthand for infix versions, such as:

`lessThan` -> `lt`
`lessThanEquals` -> `lte`
etc.
