### ISSUE TITLE
test `rotation axis angle` fails

### ISSUE THREAD

**Issue by travisfw** [romainguy/kotlin-math#27]
My matrix math skills are nothing but rust, so when I look at what [this test](https://github.com/romainguy/kotlin-math/blob/17da318aa7b3a4ae344669b068ae654a3dcbe619/src/test/kotlin/com/curiouscreature/kotlin/math/MatrixTest.kt#L228 ) is doing, I can't even.
`gradle test` fails, reporting:
```
com.curiouscreature.kotlin.math.MatrixTest > rotation axis angle FAILED
    org.junit.internal.ArrayComparisonFailure at MatrixTest.kt:229
        Caused by: java.lang.AssertionError at MatrixTest.kt:229
```
The html report says
> arrays first differed at element [2]; expected:<4.0> but was:<5.0>
>	 at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
> …

**Comment by elizagamedev** [comment]
According to [wikipedia](https://en.wikipedia.org/wiki/Rotation_matrix#Rotation_matrix_from_axis_and_angle), it looks like it should actually be 5.0.

**Comment by romainguy** [comment]
The tests are not great, they need to be rewritten.

**Comment by romainguy** [comment]
Fixed by @elizagamedev, thank you!
