### ISSUE TITLE
How to integrate this library?

### ISSUE THREAD

**Issue by cubuspl42** [romainguy/kotlin-math#30]
Is this library published (for example in Maven Central), so it can be easily consumed by a Gradle-based project? If no, what's the simplest way to use this library?

**Comment by romainguy** [comment]
It’s not on maven central no, Currently the easiest way to use it is to copy the source files in your project.

**Comment by romainguy** [comment]
You can also follow these instructions: https://github.com/romainguy/kotlin-math/pull/29/files
