### ISSUE TITLE
Is `ortho` works correctly?

### ISSUE THREAD

**Issue by desugar-64** [romainguy/kotlin-math#51]
Am I using `fun ortho(...)` wrong?

Creating an orthographic camera using the `fun ortho(l: Float, r: Float, b: Float, t: Float, n: Float, f: Float): Mat4` function produces a matrix with strange values that appear to work correctly, but as soon as you start changing the scale on the camera, you begin to notice an incorrect graphics aspect ratio(or stretching, see video below).

Replacing the `ortho` function with `android.opengl.Matrix.orthoM()` gives a correct result(aspect ratio and scale).
My code snippets:
Using `dev.romainguy.kotlin.math.MatrixKt#ortho`
```kotlin
// Camera#setProjection
fun setProjection(left: Float, right: Float, bottom: Float, top: Float) {
    projectionMatrix = ortho(left, right, bottom, top, -1.0f, 1.0f)
    viewProjectionMatrix = projectionMatrix * viewMatrix
}
```
Result: 
```
|-4.296651 0.0 0.0 -0.0|
|0.0 1.0 0.0 -0.0|
|0.0 0.0 -1.0 -0.0|
|0.0 0.0 0.0 1.0|
```

Using `android.opengl.Matrix#orthoM` and converting it to Mat4
```kotlin
// Camera#setProjection
fun setProjection(left: Float, right: Float, bottom: Float, top: Float) {
    val idMat = Mat4.identity().toFloatArray()
    Matrix.orthoM(idMat , 0, left, right, bottom, top, -1.0f, 1.0f)
    val tMat = Mat4.identity().toFloatArray()
    Matrix.transposeM(tMat , 0, idMat , 0)
    val mt = Mat4.of(*tMat)
    projectionMatrix = mt
    viewProjectionMatrix= projectionMatrix * viewMatrix
}
```
Result(correct one): 
```
|1.8708333 0.0 0.0 -0.0|
|0.0 1.0 0.0 -0.0|
|0.0 0.0 -1.0 -0.0|
|0.0 0.0 0.0 1.0|
```

How I call `camera.setProjection`:
```kotlin
camera.setProjection(
    left = -aspectRatio * zoomLevel,
    right = aspectRatio * zoomLevel,
    bottom = -zoomLevel,
    top = zoomLevel
)
```
Zoom value is changing with a mouse wheel scroll on a physical android device.
```kotlin
private fun onMouseScrolled(event: MouseScrolledEvent) {
    zoomLevel -= event.offsetY * 0.25f
    zoomLevel = zoomLevel.coerceAtLeast(0.25f)
    updateCameraProjection() // it calls camera.setProjection
}
```
Using `android.opengl.Matrix#orthoM`(works as expected):

https://user-images.githubusercontent.com/3204638/201448850-07cdd033-19ea-401a-8337-8bddf386528f.mp4

Using `dev.romainguy.kotlin.math.MatrixKt#ortho`(strange stretching instead of scaling):

https://user-images.githubusercontent.com/3204638/201448885-f6b51ee3-bd96-470c-8684-cf0dbf767c3d.mp4

**Comment by romainguy** [comment]
Sorry I missed this before. There might be a bug indeed. I’ll take a look.

**Comment by romainguy** [comment]
Ooops, there's a silly typo in `ortho()`: `r - 1` instead of `r - l` 😅

**Comment by romainguy** [comment]
The bug is now fixed. I will publish v1.5.3 asap with the fix.

**Comment by romainguy** [comment]
And turns out the test for `ortho()` used the exact set of values that worked with the typo 😭

**Comment by romainguy** [comment]
https://github.com/romainguy/kotlin-math/releases/tag/v1.5.3

**Comment by desugar-64** [comment]
Thanks @romainguy. You are the best 👍
